### ISSUE TITLE
Please add comments to your code! Especially within functions

### ISSUE THREAD

**Issue by Razvanmatis** [SilvesterSchneider/CRohM#1]
Hey Silvester. Thank you very much for your first work within this project. But please add much more comments into your code as most people here aren't familiar with that code! So it would be really helpful especially for the future as it gets bigger and more complex to have something you can read. I mean of course not every single variable should be commented but at least every method in my opinion...Thank you very much in advance!

**Comment by julianhof** [comment]
Je trouverais également utile de laisser des commentaires en allemand. Vous n'avez pas à compliquer la vie inutilement, ou qu'en pensez-vous?

**Comment by SilvesterSchneider** [comment]
? Also ich versteh nur Bahnhof. Bitte auf deutsch

**Comment by julianhof** [comment]
Genau darauf wollte ich ja heraus ;)

**Comment by Razvanmatis** [comment]
Ok verstanden. Sorry, aber bin es gewohnt von der Arbeit her, alles immer auf Englisch zu verfassen, damit es halt auch von einer größeren Gruppe von Leuten verstanden werden kann. Macht bei uns tatsächlich wenig bzw keinen Sinn.. :)

**Comment by SilvesterSchneider** [comment]
Habe vertstanden, werde mehr kommentieren.
Schließe den Issue hiermit
