### ISSUE TITLE
Login liefert nicht korrekte Rollen zurück

### ISSUE THREAD

**Issue by SilvesterSchneider** [SilvesterSchneider/CRohM#109]
> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwiSWQiOiIxIiwibmJmIjoxNTk2NzQwOTY0LCJleHAiOjE1OTczNDU3NjQsImlhdCI6MTU5Njc0MDk2NH0.YUrCekYXl1v66_jbPbbN4Dnh62OH5ei-7-tpqjKhUpw

Sorry aber das liegt wohl am Berechtigungssystem:
![image](https://user-images.githubusercontent.com/18558683/89572828-f8f0a280-d829-11ea-94d3-732e999acbb7.png)

wenn du mal deinen Token decodierst siehst dass keine Rolle vorhanden ist

_Originally posted by @SilvesterSchneider in https://github.com/SilvesterSchneider/CRohM/pull/103#issuecomment-670143665_

**Comment by Razvanmatis** [comment]
so sollte ein gültiges jwt ausschauen:

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwiSWQiOiIxIiwicm9sZSI6WyJEYXRlbnNjaHV0emJlYXVmdHJhZ3RlciIsIkFkbWlyYWxBbmFsIl0sIm5iZiI6MTU5Njc0MzIxMSwiZXhwIjoxNTk3MzQ4MDExLCJpYXQiOjE1OTY3NDMyMTF9.9eOGHYSR_oZJ3oima84PXBo67KWUuY9VinjcSC9Fo08

**Comment by Razvanmatis** [comment]
erledigt...
