### ISSUE TITLE
Exceptions auf der Landingpage

### ISSUE THREAD

**Issue by SilvesterSchneider** [SilvesterSchneider/CRohM#110]
![exceptionslandingpage](https://user-images.githubusercontent.com/18558683/89706228-eda19200-d963-11ea-9702-0d2d6633734f.gif)

@Razvanmatis

**Comment by Razvanmatis** [comment]
Schon gesehen und behoben in einem meiner aktuellen Mrs. Aber danke silva

**Comment by SilvesterSchneider** [comment]
welcher mr? dann verlinke ich den gleich

**Comment by Razvanmatis** [comment]
Ds7
