### ISSUE TITLE
Struktur der DTO's in der Backend API

### ISSUE THREAD

**Issue by julianhof** [SilvesterSchneider/CRohM#39]
Hi zusammen. 

Mir ist unklar, warum es zu vielen (aber nicht allen) Schnittstellen in der API zusätzlich zu der dto-Schnittstelle noch eine createDto-Schnittstelle gibt. Gibt es dafür einen Grund den ich nicht kenne?

Andernfalls fände ich es deutlich übersichtlicher, die createDto-Schnittstellen zu entfernen.

**Comment by SilvesterSchneider** [comment]
Also ich würde diese CreateDto und UpdateDto und normale Dto anlegen um den Input zu trennen.
Im Backend hat man somit nicht das Problem einzelne Felder zu überprüfen oder zu Null Werte zu setzen.

Als Beispiel:
Du hast folgenden Benutzer

```
public class User{
    public int Id {get;set;}
    public string Name {get;set;}
    public int Alter {get;set;}
    public string Email {get;set;}
    public string Passwort {get;set;}
}
```

Wenn du den Benutzer aus der API raus gibst benutzt du nun ein Dto das so aussehen könnte:

```
public class UserDto{
    public int Id {get;set;}
    public string Name {get;set;}
    public int Alter {get;set;}
    public string Email {get;set;}
    public string ZugriffsToken {get;set;}
}
```
Du möchtest in dem Fall verhindern, dass das Passwort eines Benutzers die API verlässt und zusätzlich fügst du ein Feld hinzu, das später zur Verifizierung benötigt wird. Das Könntest du dann so machen.
Wenn man aber einen Benutzer anlegen möchten, wollen wir nicht, dass man eine Id mitgibt oder den ZugriffsToken setzt. Außerdem benötigen wir den Zeitstempel wann dieser Benutzer vom Frontend angelegt wurde und das Objekt muss einen Namen besitzen. 
Jetzt haben wir die Möglichkeit Logik in den Controller einzubauen, welche prüft ob die Regeln alle eingehalten wurden oder eben ein neues Dto anlegen. 
Das Dto nimmt uns somit viel arbeit ab und wir können spezielle Felder und Atribute hinzufügen.
Das Dto könnte dann so aussehen:
```
public class UserCreatDto{
    [Required]
    public string Name {get;set;}
    public int Alter {get;set;}
    public string Email {get;set;}
    public Date Zeitstemepl {get;set;} 
}
```
Was haltet Ihr von dem Vorschlag?
Würde mich über Diskussion und andere Vorschläge freuen :)

**Comment by Makki93** [comment]
Hm also prinzipiell finde ich den Vorschlag schon gut,
ich verstehe auch die Thematik, die du ansprichst.
Die drei Dto's unterscheiden sich halt um ein paar Attribute die für die jeweilige Aktion wichtig sind, manche haben noch ein paar mehr, andere weniger.

Ich finde es allerdings auch störend, dass viel doppelt getippt und dementsprechend copy-pasted/ bei Änderungen nachgezogen werden muss.

Könnten wir uns nicht für jede Klasse wie z.B. User eine BasicElements-Klasse schreiben, quasi etwas, was bei jedem Zugriff benötigt wird, und von diesem Erben?
Wäre hier Name, Alter, Mail.

Dann haben wir zwar noch eine 4te °° Klasse, allerdings ist offensichtlich, worin sich unsere eigentlichen Dto's unterscheiden :)

**Comment by Razvanmatis** [comment]
Ich finde silvas Vorschlag sinnvoll und ok. Und zu markus: klar kannst du falls dir Gemeinsamkeiten auffallen, diese in eine separate dto Klasse reinpacken welche du dann halt referenziert anstatt soviel copy and pasten zu müssen. Habe ich ja auch schon gemacht..

**Comment by julianhof** [comment]
Wenn das im Backend gem. Silvers Lösung einfacher zu handhaben ist dann okay. Solange die Namensstruktur eben einheitlich ist.

Der Unterschied zwischen den CreateDto`s und den UpdateDto`s ist dann wahrscheinlich, dass bei letzteren noch eine ID dabei sein wird?

Vielleicht etwas OffTopic:
Wäre ich als Frontend-Entwickler dann verantwortlich, auch den Zeitstempel aus dem obigen Beispiel bei UserCreateDto zu setzen? Der interssiert mich aus Frontend-Sicht doch gar nicht wenn ich nen Nutzer anlegen will.

**Comment by SilvesterSchneider** [comment]
das mit dem Zeitstempel war nur so ein Beispiel. Du hast recht, so ein Zeitstempel wird meist vom Backend gesetzt ;)
