### ISSUE TITLE
Kaputte Migrationen

### ISSUE THREAD

**Issue by SilvesterSchneider** [SilvesterSchneider/CRohM#41]
In unserer Datenbank-Migration scheint irgendwas nicht ganz zu passen.
Ich bekomme Fehler wenn ich meine Datenbank lösche und sie über die Migrationen wieder aufsetzen möchte.
Ich würde allerdings nicht versuchen hier irgendwas zu fixen. Dauert zu lang.
Wir sind noch auf einem Stand wo wir die alten Migrationen weglöschen können.
Bitte bestätigt das mit einem Daumen nach oben dann werde ich das machen.

Für die Zukunft werde ich eine Anleitung schreiben wie man mit Migrationen arbeitet.

**Comment by Razvanmatis** [comment]
👍

**Comment by julianhof** [comment]
Führt das zu dem Fehler den ich gerade beim Start der WebAPI habe?

`dataContext.Database.Migrate();`

führt zu folgendem Fehler:

> Microsoft.Data.SqlClient.SqlException: "Löschen des Tabelle-Objekts "Contacts" ist nicht möglich, weil das Objekt nicht vorhanden ist oder Sie nicht die erforderliche Berechtigung haben."

**Comment by Razvanmatis** [comment]
Jap. Also entweder wartest du bis der silva den neuen Stand ohne die migration en gemergt hat oder du entfernst sie alle selber und baust dann eine neue damit das wieder läuft
