### ISSUE TITLE
3 ContactPossibilitiesCreateDto Interfaces

### ISSUE THREAD

**Issue by julianhof** [SilvesterSchneider/CRohM#43]
In frontend\src\app\shared\api-generated\api-generated.ts gibt es 3 verschiedene ContactPossibilitiesCreateDto Interfaces. Ich weiß nicht, auf welches Interface ich in meiner ContactAdd-Component zugreifen soll. 

Zeile 1262
export interface ContactPossibilitiesCreateDto {
    phoneNumber?: string | undefined;
    fax?: string | undefined;
    mail: string;
}

Zeile 1299
export interface ContactPossibilitiesCreateDto {
    phoneNumber?: string | undefined;
    faxnumber?: string | undefined;
    email: string;
    employees?: ContactCreateDto[] | undefined;
}

Zeile 1307
export interface ContactPossibilitiesCreateDto {
    phoneNumber?: string | undefined;
    faxnumber?: string | undefined;
    email: string;
}

**Comment by Razvanmatis** [comment]
also ich kann dir bestätigen dass das erste interface das korrekte ist..wieso die anderen altlasten mit angezeigt werden, ist eine gute frage,,ich analysiere das mal weng genauer..

**Comment by Razvanmatis** [comment]
also das problem scheint sich von selber gelöst zu haben, da aktuell nur einmal das interface in der datei auftaucht

**Comment by julianhof** [comment]
Vielleicht bei dir lokal? Hier im Master finde ich nach wie vor die drei Interfaces an den drei von mir genannten Stellen... 

Leider reicht es auch nicht zu wissen, dass nur das eine richtig ist weil die anderen beiden es verhindern, das Interface zu nutzen. Kann ich die beiden einfach löschen? Tu ich eigentlich ungern in autogeneriertem Code.

**Comment by Razvanmatis** [comment]
ne. ich würde darauf warten bis einer der aktuelleren merge requests gemergt wurde. dort befindet sich dann nur ein interface davon drin..

**Comment by julianhof** [comment]
Okay. Passt jetzt für mich. Danke!
