### ISSUE TITLE
Contact UpdateAsync überspeichert potentiell Werte in der DB mit Null werten

### ISSUE THREAD

**Issue by Makki93** [SilvesterSchneider/CRohM#48]
Aktuell werden durch die Methode UpdateAsync im ContactRepository alle Werte von einem Contact der mit der angegebenen id (Übergabeparameter) mit den Werten vom übergebenen Contact (Übergabeparameter) überschrieben.

Wenn dies durch einen Aufruf vom ContactController durchgeführt wird, welcher die Daten vom FrontEnd per Dto bekommt entsteht folgendes Problem:

Das FrontEnd hat evtl. nur selektierte Parameter per Dto bekommen, sagen wir 6 von 8 Attributen wurden übergeben. Es sind jedoch mehr gültige in der Datenbank vorhanden, die auch nicht durch Null-Attribute überschrieben werden sollen (nur weil das Dto nicht alle Attribute der DB bereit stellt).

Auf der anderen Seite sollte es evtl. auch möglich sein, dass bei einer Contact-Eingabemaske ein paar Einträge raus gelöscht werden sollen, wie z.B. eine nicht mehr gültige TelNr.

Vorschlag: Es würde evtl. Sinn machen, eine UpdateAsync-Methode für die jeweiligen Dto's zu machen.

**Comment by SilvesterSchneider** [comment]
hier gibt es eine recht einfache Lösung.

Im MappingProfil kann man anlegen dass nur Felder gemappet werden die nicht null sind. Wenn man die map auf das zuvor aus der Datenbank gezogene Entity/Model macht, dann erkennt der Changetracker von EF core, dass sich nur gewisse Felder verändert haben

**Comment by Makki93** [comment]
Wo finde ich das MappingProfil? Das muss doch trotzdem in der UpdateAsync-Methode bekannt sein oder? Bekommt das auch das MappingProfil? Aktuell ist es in der UpdateAsync-Methode so umgesetzt, dass ein neues Objekt für Contact erstellt wird, welches das Ursprüngliche ersetzt (mit eben potentiell Null-Feldern).

**Comment by Razvanmatis** [comment]
ist es denn hier nicht eher so, als das die leeren attribute, wie du sie hier nennst markus dann einfach mit einem leeren string überschrieben würden, was aber auch total in ordnung wäre? weil man möchte ja eventuelle im nachgang informationen streichen..ich denke das alles so passt wie es aktuell implementiert ist...

**Comment by SilvesterSchneider** [comment]
Sollte sich ja dann mit deinem Branch:
https://github.com/SilvesterSchneider/CRohM/tree/US9
erledigen
