### ISSUE TITLE
Keine Kontakte bei der Kontaktübersicht

### ISSUE THREAD

**Issue by SilvesterSchneider** [SilvesterSchneider/CRohM#54]
Wenn man in der Live Umgebung auf die Kontaktübersicht navigiert, werden in der Entwicklerkonsole einige Fehler geschmissen und der Request zur API bricht mit Statuscode 500 ab

**Comment by Razvanmatis** [comment]
ist das erledigt? ich glaube schon @SilvesterSchneider

**Comment by SilvesterSchneider** [comment]
nein, aktuell noch nicht. Aber im Moment ist auch nicht der aktuellste Stand im live Modus.
Wenn mein Pull Request https://github.com/SilvesterSchneider/CRohM/pull/67 durch ist sollten wir wieder auf dem aktuellen Stand sein.
