### ISSUE TITLE
Unterschiedliche Validierung im Frontend und Backend

### ISSUE THREAD

**Issue by michellemrtn** [SilvesterSchneider/CRohM#58]
Die Validierungen im Frontend und Backend laufen relativ oft auseinander, und sollten vereinheitlicht werden.

Teilweise ist die Backend-Validierung strenger, sodass man bei validen Werten im Frontend Fehlermeldungen vom Backend zurückbekommt.
Zum Beispiel beim AddressCreateDto, hier wird im Backend bei den Strings geprüft, dass diese nicht leer sind, im Frontend jedoch nicht.

An anderen Stellen ist die Frontend-Validierung strenger, zum Beispiel bei der Telefonnummer, welche im Frontend zwingend mit einer 0 beginnen muss.

**Comment by Razvanmatis** [comment]
habe dieses thema angepasst mit dem aktuellsten MR, wo die punkte vom markus bearbeitet wurden...
