### ISSUE TITLE
REST-Resourcen-Absicherung fehlt

### ISSUE THREAD

**Issue by michellemrtn** [SilvesterSchneider/CRohM#85]
Manche REST-Ressourcen (z.B. /event oder /contact) sind nicht abgesichert, und können auch ohne JWT abgerufen werden.

**Comment by Makki93** [comment]
wurde das schon erledigt?

**Comment by michellemrtn** [comment]
Ja, ist durch die Umsetzung des Rollenkonzepts erledigt.
